root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = "bin/narciso"
cmd = """templ generate && \
 	bunx tailwindcss -i web/assets/css/main.css -o bin/assets/css/styles.css && \
	go build -o bin/narciso cmd/web/main.go && \
	cp -r web/assets bin/assets && \
	cp -r web/static bin/static
	"""

delay = 100
exclude_dir = [
    "tmp",
    "vendor",
    "testdata",
    "node_modules",
    "deployments",
    "bin",
]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 8080
enabled = true
proxy_port = 8090

[screen]
clear_on_rebuild = false
keep_scroll = true
